/** Generated by scripts/generate-environment.mjs — do not edit manually. */
export const environment = {
  production: true,
  apiUrl: 'http://localhost:3001/api',
  socketUrl: 'http://localhost:3001',
  googleClientId: '',
};
